---
kind: pipeline
name: verify

steps:
- name: vendor
  image: golang:1.11
  commands:
  - echo "vendor"
- name: format
  image: golang:1.11
  commands:
  - echo "format"
- name: lint
  image: golang:1.11
  commands:
  - echo "lint"

---
kind: pipeline
name: test

steps:
- name: test
  image: golang:1.10
  commands:
  - go test -v
  depends_on:
    - verify

---
kind: pipeline
name: build

steps:
- name: test
  image: golang:1.10
  commands:
  - go build
  depends_on:
    - test
